### ISSUE TITLE
Error: "string" is not allowed to be empty

### ISSUE THREAD

**Issue by spantheslayer** [durbintech/sample-app#1]
`yarn start` throws below error.

```
yarn run v1.22.10
$ ts-node src/index.ts
Error: "string" is not allowed to be empty
    at Object.validate [as default] (/home/span/sample-app/node_modules/@durbintech/app-webhooks/src/validators/string_validator.ts:9:20)
    at Store.set [as client_id] (/home/span/sample-app/node_modules/@durbintech/app-webhooks/src/store.ts:47:20)
    at Object.set (/home/span/sample-app/node_modules/@durbintech/app-webhooks/src/index.ts:60:22)
    at /home/span/sample-app/src/index.ts:43:9
    at step (/home/span/sample-app/src/index.ts:33:23)
    at Object.next (/home/span/sample-app/src/index.ts:14:53)
    at /home/span/sample-app/src/index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/span/sample-app/src/index.ts:4:12)
    at main (/home/span/sample-app/src/index.ts:6:14)
```

After going through the codebase I found the error lies with @durbintech/app-webhooks npm package. 
The issue is related with `joi validation`. 

Issue causing at `APP-WEBHOOKS>src>validators>string_validator.ts` `line 5` 
 `string: Joi.string().required(),`

My proposed change 
`string: Joi.string().allow(''),`

Here's the link 
https://github.com/durbintech/app-webhooks/blob/main/src/validators/string_validator.ts#:~:text=string%3A%20Joi.string().required()%2C

**Comment by sandipndev** [comment]
Are the `CLIENT_ID` and `CLIENT_SECRET` environment variables being set correctly?

**Comment by spantheslayer** [comment]
Those two fields are empty and I dont have access to those variables too.

**Comment by sandipndev** [comment]
You can set the same from the `.env` file. I did a check and everything seems to work fine, do another pull of this repository for a minor change to the version scheme.

**Comment by spantheslayer** [comment]
server did spin up successfully. closing the issue.
